package com.bitian.db.mybatis_helper.tk.apt;

import javax.annotation.processing.*;
import javax.lang.model.SourceVersion;
import javax.lang.model.element.*;
import javax.lang.model.util.Elements;
import javax.tools.Diagnostic;
import javax.tools.JavaFileObject;
import java.io.IOException;
import java.io.Writer;
import java.util.Set;

@SupportedAnnotationTypes("javax.persistence.Table")
@SupportedSourceVersion(SourceVersion.RELEASE_8)
public class TkMetaProcessor extends AbstractProcessor {

    private Elements elementUtils;
    private Filer filer;
    private Messager messager;

    @Override
    public synchronized void init(ProcessingEnvironment processingEnv) {
        super.init(processingEnv);
        elementUtils = processingEnv.getElementUtils();
        filer = processingEnv.getFiler();
        messager = processingEnv.getMessager();
    }

    @Override
    public boolean process(Set<? extends TypeElement> annotations, RoundEnvironment roundEnv) {
        if (roundEnv.processingOver()) {
            return false;
        }
        try {
            for (TypeElement annotation : annotations) {
                Set<? extends Element> annotatedElements = roundEnv.getElementsAnnotatedWith(annotation);
                for (Element element : annotatedElements) {
                    if (element.getKind() == ElementKind.CLASS) {
                        generateMetaClass((TypeElement) element);
                    }
                }
            }
        } catch (Exception e) {
            messager.printMessage(Diagnostic.Kind.ERROR, "Internal error in TkMetaProcessor: " + e.getMessage());
        }
        return false; // 返回 false 让其他处理器（如 Lombok）也能看到这些注解
    }

    private void generateMetaClass(TypeElement classElement) throws IOException {
        String packageName = elementUtils.getPackageOf(classElement).getQualifiedName().toString();
        String className = classElement.getSimpleName().toString();
        String qClassName = "Q" + className;

        // 获取 @Table 注解中的表名
        AnnotationMirror tableAnnotation = getAnnotation(classElement, "javax.persistence.Table");
        String tableName = getAnnotationValue(tableAnnotation, "name");
        if (tableName == null || tableName.isEmpty()) {
            tableName = camelToUnderline(className);
        }

        JavaFileObject builderFile;
        try {
            builderFile = filer.createSourceFile(packageName + "." + qClassName);
        } catch (javax.annotation.processing.FilerException e) {
            // IDEA 增量编译或多 Round 环境下如果文件已存在，直接忽略重复创建
            return;
        }

        try (Writer writer = builderFile.openWriter()) {
            writer.write("package " + packageName + ";\n\n");
            writer.write("import com.bitian.db.mybatis_helper.tk.meta.TkTable;\n");
            writer.write("import com.bitian.db.mybatis_helper.tk.meta.TkColumn;\n\n");
            writer.write("/**\n");
            writer.write(" * " + className + " 的静态强类型元模型\n");
            writer.write(" * 编译时自动生成，请勿手动修改（Auto-generated by TkMetaProcessor）\n");
            writer.write(" */\n");
            writer.write("public class " + qClassName + " extends TkTable {\n\n");

            String staticFieldName = sanitizeFieldName(tableName).toUpperCase();
            writer.write("    public static final " + qClassName + " " + staticFieldName + " = new " + qClassName + "(\"" + tableName + "\");\n\n");

            writer.write("    public static " + qClassName + " as(String alias) {\n");
            writer.write("        return new " + qClassName + "(alias);\n");
            writer.write("    }\n\n");

            writer.write("    public " + qClassName + "(String alias) {\n");
            writer.write("        super(\"" + tableName + "\", alias);\n");
            writer.write("    }\n\n");

            java.util.List<String> fieldNames = new java.util.ArrayList<>();
            // 遍历字段
            for (Element enclosed : classElement.getEnclosedElements()) {
                if (enclosed.getKind() == ElementKind.FIELD) {
                    VariableElement field = (VariableElement) enclosed;
                    // 忽略 static 和 @Transient
                    if (field.getModifiers().contains(Modifier.STATIC)) continue;
                    if (getAnnotation(field, "javax.persistence.Transient") != null) continue;

                    // 过滤复杂关联对象（只保留基本类型、包装类、String、时间类型、高精度数字、枚举）
                    if (!isSupportedType(field)) continue;

                    String fieldName = field.getSimpleName().toString();
                    String colName = fieldName;

                    // 检查是否有 @Column 并且配置了 name
                    AnnotationMirror colAnnotation = getAnnotation(field, "javax.persistence.Column");
                    if (colAnnotation != null) {
                        String nameVal = getAnnotationValue(colAnnotation, "name");
                        if (nameVal != null && !nameVal.isEmpty()) {
                            colName = nameVal;
                        } else {
                            colName = camelToUnderline(fieldName);
                        }
                    } else {
                        // 默认驼峰转下划线
                    colName = camelToUnderline(fieldName);
                }

                String constantFieldName = sanitizeFieldName(colName).toUpperCase();
                writer.write("    public final TkColumn " + constantFieldName + " = createColumn(\"" + colName + "\");\n");
                fieldNames.add(constantFieldName);
            }
        }

            if (!fieldNames.isEmpty()) {
                writer.write("\n    public final TkColumn[] ALL = new TkColumn[] { " + String.join(", ", fieldNames) + " };\n");
            }

            writer.write("}\n");
        }
    }

    private AnnotationMirror getAnnotation(Element element, String annotationName) {
        for (AnnotationMirror mirror : element.getAnnotationMirrors()) {
            if (mirror.getAnnotationType().toString().equals(annotationName)) {
                return mirror;
            }
        }
        return null;
    }

    private boolean isSupportedType(VariableElement field) {
        javax.lang.model.type.TypeMirror typeMirror = field.asType();
        if (typeMirror.getKind().isPrimitive()) {
            return true;
        }
        if (typeMirror.getKind() == javax.lang.model.type.TypeKind.DECLARED) {
            Element element = ((javax.lang.model.type.DeclaredType) typeMirror).asElement();
            if (element != null && element.getKind() == ElementKind.ENUM) {
                return true;
            }
            if (element instanceof TypeElement) {
                String className = ((TypeElement) element).getQualifiedName().toString();
                if (className.startsWith("java.lang.")) {
                    return true;
                }
                if (className.equals("java.math.BigDecimal") || className.equals("java.math.BigInteger") ||
                    className.equals("java.util.Date") || className.startsWith("java.sql.") || 
                    className.startsWith("java.time.")) {
                    return true;
                }
            }
        }
        return false;
    }

    private String getAnnotationValue(AnnotationMirror annotationMirror, String key) {
        if (annotationMirror == null) return null;
        for (ExecutableElement executableElement : annotationMirror.getElementValues().keySet()) {
            if (executableElement.getSimpleName().toString().equals(key)) {
                AnnotationValue value = annotationMirror.getElementValues().get(executableElement);
                // AnnotationValue.toString() may return quotes if it's a string literal, e.g., "sys_user"
                String strValue = value.getValue().toString();
                return strValue;
            }
        }
        return null;
    }

    private String sanitizeFieldName(String colName) {
        if (colName == null) return "";
        // 移除数据库转义符：反引号、方括号、双引号等
        return colName.replaceAll("[`\\[\\]\"\\s]", "");
    }

    private String camelToUnderline(String param) {
        if (param == null || param.isEmpty()) {
            return "";
        }
        int len = param.length();
        StringBuilder sb = new StringBuilder(len);
        for (int i = 0; i < len; i++) {
            char c = param.charAt(i);
            if (Character.isUpperCase(c)) {
                if (i > 0) sb.append('_');
                sb.append(Character.toLowerCase(c));
            } else {
                sb.append(c);
            }
        }
        return sb.toString();
    }
}
